version: '1'
services:
  web:
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - API_KEY=sk-fetdccvrxjtkihpvzhovtageofnbpvmvpsnxmtprfprgowfg
